Here is a clean **Markdown cell** explaining each column 👇

---

```markdown
# 📊 Chicago Crime Dataset – Column Descriptions

## 🆔 Identifiers

### Unnamed: 0
- Extra index column created during data export
- ❌ Not useful → should be dropped

### ID
- Unique identifier for each crime record
- Used to distinguish entries
- ❌ Not useful for modeling (no predictive value)

### Case Number
- Unique case reference used by police
- May have slight missing values
- ❌ Not useful for modeling

---

## 🕒 Date & Time

### Date
- Date and time when the crime occurred
- Useful for extracting:
  - hour
  - day
  - month

### Updated On
- Last time the record was updated
- Not very useful for prediction
- Can be dropped or ignored

### Year
- Year of the crime occurrence
- Can be treated as a time feature

---

## 📍 Location (Text-Based)

### Block
- Approximate street address (e.g., "001XX W MADISON ST")
- Represents area, not exact location

### Location Description
- Type of location where crime occurred
- Examples: STREET, RESIDENCE, SCHOOL

### Location
- Combined Latitude & Longitude as text
- ❌ Redundant (already have Lat/Long)

---

## 📍 Location (Geographic)

### Latitude
- North-South geographic coordinate
- Continuous numerical feature

### Longitude
- East-West geographic coordinate
- Continuous numerical feature

### X Coordinate
- Local map projection coordinate (horizontal)
- ❌ Redundant with Latitude/Longitude

### Y Coordinate
- Local map projection coordinate (vertical)
- ❌ Redundant with Latitude/Longitude

---

## 🏙️ Administrative / Region-Based

### Beat
- Smallest police patrol area
- Used by police for operations
- Categorical

### District
- Police district where crime occurred
- Larger than Beat
- Categorical

### Ward
- Political division of Chicago
- Used for elections and governance
- Categorical

### Community Area
- Neighborhood grouping (77 areas)
- Used for analysis and statistics
- Categorical

---

## 🚔 Crime Details

### IUCR
- Illinois Uniform Crime Reporting code
- Encodes type of crime

### Primary Type
- Main category of crime
- Example: THEFT, BATTERY, ASSAULT

### Description
- Detailed description of the crime
- More specific than Primary Type

### FBI Code
- Crime classification used by the FBI
- Groups crimes into broader categories

---

## ⚖️ Crime Characteristics

### Arrest
- Whether an arrest was made
- Binary (True/False)

### Domestic
- Indicates if crime was domestic-related
- Binary (True/False)

---

## 🧠 Summary Notes

- Many columns describe **location in different ways**
- Some features are **redundant**:
  - Latitude/Longitude vs X/Y vs Location
- Some numeric columns are actually **categorical**:
  - Beat, District, Ward, Community Area
- Some columns should be **dropped**:
  - Unnamed: 0, ID, Case Number, X/Y, Location

---
```

In [51]:
import sqlite3
import pandas as pd
import numpy as np
'''
# Connect to the .db file
conn = sqlite3.connect(r"D:\Courses\Data mining\Assignment 1\data\Chicago.db")
'''

<>:6: SyntaxWarning: invalid escape sequence '\C'
<>:6: SyntaxWarning: invalid escape sequence '\C'
/tmp/ipykernel_724/660968462.py:6: SyntaxWarning: invalid escape sequence '\C'
  conn = sqlite3.connect(r"D:\Courses\Data mining\Assignment 1\data\Chicago.db")

'\n# Connect to the .db file\nconn = sqlite3.connect(r"D:\\Courses\\Data mining\\Assignment 1\\data\\Chicago.db")\n'

In [52]:
'''
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
'''

'\ncursor = conn.cursor()\n\ncursor.execute("SELECT name FROM sqlite_master WHERE type=\'table\';")\ntables = cursor.fetchall()\n'

In [53]:
#tables

In [54]:
#df = pd.read_sql("SELECT * FROM Chicago_Crimes;", conn)

In [55]:
df=pd.read_csv("/content/Chicago_Crimes.csv")

In [56]:
df

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,975063,1362430,G052547,01/25/2001 09:30:55 PM,059XX S INDIANA AV,1812,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,STREET,1.0,...,NaN,NaN,18,1178661.0,1865453.0,2001.0,08/17/2015 03:03:40 PM,41.786104,-87.620479,"(41.786104493, -87.620479)"
1,968646,1354040,G054426,01/26/2001 07:00:38 PM,027XX N LAWNDALE AV,0560,ASSAULT,SIMPLE,RESIDENCE,0.0,...,NaN,NaN,08A,1151292.0,1917840.0,2001.0,08/17/2015 03:03:40 PM,41.930439,-87.719455,"(41.930439494, -87.719454651)"
2,968645,1354039,G058256,01/28/2001 05:00:00 PM,048XX W FULLERTON AV,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,DRUG STORE,0.0,...,NaN,NaN,26,1143967.0,1915568.0,2001.0,08/17/2015 03:03:40 PM,41.924346,-87.746430,"(41.924345661, -87.74642975)"
3,968644,1354038,G056929,01/27/2001 09:13:56 PM,052XX W DIVISION ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,STREET,0.0,...,NaN,NaN,26,1140886.0,1907525.0,2001.0,08/17/2015 03:03:40 PM,41.902332,-87.757949,"(41.902332083, -87.757949044)"
4,968643,1354036,G058258,01/06/2001 04:00:00 PM,022XX S KEDVALE AV,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,0.0,...,NaN,NaN,26,1149218.0,1888837.0,2001.0,08/17/2015 03:03:40 PM,41.850893,-87.727828,"(41.850892653, -87.727828281)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52078,91287,10200472,HY387851,08/13/2015 03:00:00 PM,003XX W 103RD ST,0560,ASSAULT,SIMPLE,DEPARTMENT STORE,0.0,...,9.0,49.0,08A,1175895.0,1836626.0,2015.0,02/10/2018 03:50:01 PM,41.707062,-87.631483,"(41.707062135, -87.631482564)"
52079,91286,10200468,HY388077,08/18/2015 07:16:00 PM,010XX N LATROBE AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,0.0,...,37.0,25.0,08B,1141167.0,1906522.0,2015.0,08/31/2015 03:43:09 PM,41.899575,-87.756942,"(41.899574557, -87.756941626)"
52080,91285,10200467,HY388096,08/18/2015 07:15:00 PM,031XX S PULASKI RD,0460,BATTERY,SIMPLE,PARKING LOT/GARAGE(NON.RESID.),1.0,...,22.0,30.0,08B,1150206.0,1883566.0,2015.0,02/10/2018 03:50:01 PM,41.836409,-87.724339,"(41.83640918, -87.724339262)"
52081,91283,10200466,HY388067,08/18/2015 07:10:00 PM,066XX N ASHLAND AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,1.0,...,40.0,1.0,14,1164409.0,1944119.0,2015.0,02/10/2018 03:50:01 PM,42.002282,-87.670506,"(42.002282312, -87.670505657)"
52082,91282,10200465,HY387969,08/18/2015 05:28:00 PM,015XX,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df.columns

Index(['Unnamed: 0', 'ID', 'Case Number', 'Date', 'Block', 'IUCR',
       'Primary Type', 'Description', 'Location Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code',
       'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude',
       'Longitude', 'Location'],
      dtype='object')

## 1 - Dimensionality Reduction

##### Not useful for predictions and analysis

In [58]:
cols_to_drop = [
    'Unnamed: 0',
    'ID',
    'Case Number'
]

df = df.drop(columns=cols_to_drop, errors='ignore')

In [59]:
df = df.drop(columns=['X Coordinate', 'Y Coordinate']) #gives the same info as latitude and longitude

In [60]:
df = df.drop(columns=['IUCR', 'FBI Code']) # These codes are not human-readable and don't add much value for analysis.

In [61]:
df[['Year','Date']]

         Year                    Date
0      2001.0  01/25/2001 09:30:55 PM
1      2001.0  01/26/2001 07:00:38 PM
2      2001.0  01/28/2001 05:00:00 PM
3      2001.0  01/27/2001 09:13:56 PM
4      2001.0  01/06/2001 04:00:00 PM
...       ...                     ...
52078  2015.0  08/13/2015 03:00:00 PM
52079  2015.0  08/18/2015 07:16:00 PM
52080  2015.0  08/18/2015 07:15:00 PM
52081  2015.0  08/18/2015 07:10:00 PM
52082     NaN  08/18/2015 05:28:00 PM

[52083 rows x 2 columns]

## 2 -  Handling missing values

In [62]:
df.isnull().sum()

Date                        0
Block                       0
Primary Type                1
Description                 1
Location Description      164
Arrest                      1
Domestic                    1
Beat                        1
District                    1
Ward                    23338
Community Area          23245
Year                        1
Updated On                  1
Latitude                 1702
Longitude                1702
Location                 1702
dtype: int64

### 1 - Categorical Values

In [63]:
# calculate the percentage of missing values for each categorical column
cat_cols = [
    'Date',
    'Block',
    'Primary Type',
    'Description',
    'Location Description',
    'Arrest',
    'Domestic',
    'Beat',
    'District',
    'Ward',
    'Community Area',
    'Year',
    'Updated On',
    'Location'
]

missing_percent_cat = df[cat_cols].isnull().mean() * 100
print(missing_percent_cat)

Date                     0.000000
Block                    0.000000
Primary Type             0.001920
Description              0.001920
Location Description     0.314882
Arrest                   0.001920
Domestic                 0.001920
Beat                     0.001920
District                 0.001920
Ward                    44.809247
Community Area          44.630686
Year                     0.001920
Updated On               0.001920
Location                 3.267861
dtype: float64

In [64]:
#columns with more than 0% missing values in categorical columns
cols_with_missing_cat = missing_percent_cat[missing_percent_cat > 0].index.tolist()
cols_with_missing_cat

['Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Beat',
 'District',
 'Ward',
 'Community Area',
 'Year',
 'Updated On',
 'Location']

In [65]:
# handling them by taking the mode of each column and filling the missing values with it
for col in cols_with_missing_cat:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

/tmp/ipykernel_724/3955084587.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [66]:
#checking if there are still missing values in categorical columns
missing_percent_cat_after = df[cat_cols].isnull().mean() * 100
missing_percent_cat_after

Date                    0.0
Block                   0.0
Primary Type            0.0
Description             0.0
Location Description    0.0
Arrest                  0.0
Domestic                0.0
Beat                    0.0
District                0.0
Ward                    0.0
Community Area          0.0
Year                    0.0
Updated On              0.0
Location                0.0
dtype: float64

### 2 - Numerical values

In [67]:
df[['Latitude', 'Longitude']].isnull().sum() # only real numerical columns

Latitude     1702
Longitude    1702
dtype: int64

In [68]:
df['Community Area'].isnull().sum()

np.int64(0)

### We will now use the " Community area " column to fill the missing values in "latitude" & "longitude"

In [69]:
df['Latitude'] = df.groupby('Community Area')['Latitude'].transform(
    lambda x: x.fillna(x.median())
)

In [70]:
df['Longitude'] = df.groupby('Community Area')['Longitude'].transform(lambda x: x.fillna(x.median()))

In [71]:
df[['Latitude', 'Longitude']].isnull().sum()

Latitude     0
Longitude    0
dtype: int64

### Check for duplicates

In [72]:
duplicates = df.duplicated().sum()
duplicates

np.int64(58)

In [73]:
df = df.drop_duplicates()

In [74]:
df

,Date,Block,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Updated On,Latitude,Longitude,Location
0,01/25/2001 09:30:55 PM,059XX S INDIANA AV,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,STREET,1.0,0.0,233.0,2.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.786104,-87.620479,"(41.786104493, -87.620479)"
1,01/26/2001 07:00:38 PM,027XX N LAWNDALE AV,ASSAULT,SIMPLE,RESIDENCE,0.0,0.0,2524.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.930439,-87.719455,"(41.930439494, -87.719454651)"
2,01/28/2001 05:00:00 PM,048XX W FULLERTON AV,OTHER OFFENSE,HARASSMENT BY TELEPHONE,DRUG STORE,0.0,0.0,2521.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.924346,-87.746430,"(41.924345661, -87.74642975)"
3,01/27/2001 09:13:56 PM,052XX W DIVISION ST,OTHER OFFENSE,HARASSMENT BY TELEPHONE,STREET,0.0,0.0,2532.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.902332,-87.757949,"(41.902332083, -87.757949044)"
4,01/06/2001 04:00:00 PM,022XX S KEDVALE AV,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,0.0,1.0,1013.0,10.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.850893,-87.727828,"(41.850892653, -87.727828281)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52078,08/13/2015 03:00:00 PM,003XX W 103RD ST,ASSAULT,SIMPLE,DEPARTMENT STORE,0.0,0.0,511.0,5.0,9.0,49.0,2015.0,02/10/2018 03:50:01 PM,41.707062,-87.631483,"(41.707062135, -87.631482564)"
52079,08/18/2015 07:16:00 PM,010XX N LATROBE AVE,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,0.0,1.0,1524.0,15.0,37.0,25.0,2015.0,08/31/2015 03:43:09 PM,41.899575,-87.756942,"(41.899574557, -87.756941626)"
52080,08/18/2015 07:15:00 PM,031XX S PULASKI RD,BATTERY,SIMPLE,PARKING LOT/GARAGE(NON.RESID.),1.0,0.0,1031.0,10.0,22.0,30.0,2015.0,02/10/2018 03:50:01 PM,41.836409,-87.724339,"(41.83640918, -87.724339262)"
52081,08/18/2015 07:10:00 PM,066XX N ASHLAND AVE,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,1.0,0.0,2432.0,24.0,40.0,1.0,2015.0,02/10/2018 03:50:01 PM,42.002282,-87.670506,"(42.002282312, -87.670505657)"
52082,08/18/2015 05:28:00 PM,015XX,THEFT,SIMPLE,STREET,0.0,0.0,1834.0,8.0,42.0,25.0,2015.0,02/10/2018 03:50:01 PM,41.870932,-87.672047,"(41.976200173, -87.905312411)"

## 3 - Feature Transformation

In [75]:
df['Date']

0        01/25/2001 09:30:55 PM
1        01/26/2001 07:00:38 PM
2        01/28/2001 05:00:00 PM
3        01/27/2001 09:13:56 PM
4        01/06/2001 04:00:00 PM
                  ...
52078    08/13/2015 03:00:00 PM
52079    08/18/2015 07:16:00 PM
52080    08/18/2015 07:15:00 PM
52081    08/18/2015 07:10:00 PM
52082    08/18/2015 05:28:00 PM
Name: Date, Length: 52025, dtype: object

In [76]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='%m/%d/%Y %I:%M:%S %p',
    errors='coerce' # turns invalid parsing into NaT (Not a Time) instead of raising an error
)

In [77]:
df['Date'].head()

0   2001-01-25 21:30:55
1   2001-01-26 19:00:38
2   2001-01-28 17:00:00
3   2001-01-27 21:13:56
4   2001-01-06 16:00:00
Name: Date, dtype: datetime64[ns]

In [78]:
df['Date'].isnull().sum()

np.int64(0)

In [79]:
df['Month'] = df['Date'].dt.month
df['Month']

0        1
1        1
2        1
3        1
4        1
        ..
52078    8
52079    8
52080    8
52081    8
52082    8
Name: Month, Length: 52025, dtype: int32

In [80]:
df['DayOfWeek'] = df['Date'].dt.dayofweek
df['DayOfWeek']

'''

0 → Monday
1 → Tuesday
2 → Wednesday
3 → Thursday
4 → Friday
5 → Saturday
6 → Sunday

'''

'\n\n0 → Monday\n1 → Tuesday\n2 → Wednesday\n3 → Thursday\n4 → Friday\n5 → Saturday\n6 → Sunday\n\n'

In [81]:
df['Hour'] = df['Date'].dt.hour
df['Hour']

0        21
1        19
2        17
3        21
4        16
         ..
52078    15
52079    19
52080    19
52081    19
52082    17
Name: Hour, Length: 52025, dtype: int32

In [82]:
df[['Date', 'Month', 'DayOfWeek', 'Hour','Year']]

                     Date  Month  DayOfWeek  Hour    Year
0     2001-01-25 21:30:55      1          3    21  2001.0
1     2001-01-26 19:00:38      1          4    19  2001.0
2     2001-01-28 17:00:00      1          6    17  2001.0
3     2001-01-27 21:13:56      1          5    21  2001.0
4     2001-01-06 16:00:00      1          5    16  2001.0
...                   ...    ...        ...   ...     ...
52078 2015-08-13 15:00:00      8          3    15  2015.0
52079 2015-08-18 19:16:00      8          1    19  2015.0
52080 2015-08-18 19:15:00      8          1    19  2015.0
52081 2015-08-18 19:10:00      8          1    19  2015.0
52082 2015-08-18 17:28:00      8          1    17  2015.0

[52025 rows x 5 columns]

In [83]:
df = df.drop(columns=['Date']) # We don't need the original 'Date' column anymore since we have extracted the relevant features from it.

In [84]:
df

,Block,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,Updated On,Latitude,Longitude,Location,Month,DayOfWeek,Hour
0,059XX S INDIANA AV,NARCOTICS,POSS: CANNABIS MORE THAN 30GMS,STREET,1.0,0.0,233.0,2.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.786104,-87.620479,"(41.786104493, -87.620479)",1,3,21
1,027XX N LAWNDALE AV,ASSAULT,SIMPLE,RESIDENCE,0.0,0.0,2524.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.930439,-87.719455,"(41.930439494, -87.719454651)",1,4,19
2,048XX W FULLERTON AV,OTHER OFFENSE,HARASSMENT BY TELEPHONE,DRUG STORE,0.0,0.0,2521.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.924346,-87.746430,"(41.924345661, -87.74642975)",1,6,17
3,052XX W DIVISION ST,OTHER OFFENSE,HARASSMENT BY TELEPHONE,STREET,0.0,0.0,2532.0,25.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.902332,-87.757949,"(41.902332083, -87.757949044)",1,5,21
4,022XX S KEDVALE AV,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,0.0,1.0,1013.0,10.0,42.0,25.0,2001.0,08/17/2015 03:03:40 PM,41.850893,-87.727828,"(41.850892653, -87.727828281)",1,5,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52078,003XX W 103RD ST,ASSAULT,SIMPLE,DEPARTMENT STORE,0.0,0.0,511.0,5.0,9.0,49.0,2015.0,02/10/2018 03:50:01 PM,41.707062,-87.631483,"(41.707062135, -87.631482564)",8,3,15
52079,010XX N LATROBE AVE,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,0.0,1.0,1524.0,15.0,37.0,25.0,2015.0,08/31/2015 03:43:09 PM,41.899575,-87.756942,"(41.899574557, -87.756941626)",8,1,19
52080,031XX S PULASKI RD,BATTERY,SIMPLE,PARKING LOT/GARAGE(NON.RESID.),1.0,0.0,1031.0,10.0,22.0,30.0,2015.0,02/10/2018 03:50:01 PM,41.836409,-87.724339,"(41.83640918, -87.724339262)",8,1,19
52081,066XX N ASHLAND AVE,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,1.0,0.0,2432.0,24.0,40.0,1.0,2015.0,02/10/2018 03:50:01 PM,42.002282,-87.670506,"(42.002282312, -87.670505657)",8,1,19
52082,015XX,THEFT,SIMPLE,STREET,0.0,0.0,1834.0,8.0,42.0,25.0,2015.0,02/10/2018 03:50:01 PM,41.870932,-87.672047,"(41.976200173, -87.905312411)",8,1,17

In [85]:
df['Primary Type'].value_counts()

Primary Type
THEFT                                10780
BATTERY                               8997
CRIMINAL DAMAGE                       5419
NARCOTICS                             5340
OTHER OFFENSE                         3517
DECEPTIVE PRACTICE                    3300
ASSAULT                               2997
BURGLARY                              2643
MOTOR VEHICLE THEFT                   2443
ROBBERY                               1982
CRIMINAL TRESPASS                     1362
PROSTITUTION                           560
WEAPONS VIOLATION                      543
OFFENSE INVOLVING CHILDREN             502
CRIM SEXUAL ASSAULT                    367
PUBLIC PEACE VIOLATION                 342
SEX OFFENSE                            279
INTERFERENCE WITH PUBLIC OFFICER       162
LIQUOR LAW VIOLATION                   117
GAMBLING                                94
ARSON                                   89
KIDNAPPING                              81
STALKING                                34
INTIMIDATION                            30
CRIMINAL SEXUAL ASSAULT                 19
OBSCENITY                               14
NON-CRIMINAL                             3
HUMAN TRAFFICKING                        2
HOMICIDE                                 2
NON - CRIMINAL                           2
RITUALISM                                1
OTHER NARCOTIC VIOLATION                 1
CONCEALED CARRY LICENSE VIOLATION        1
Name: count, dtype: int64

In [86]:
df['Primary Type'].nunique()

33

In [87]:
df['Location Description'].value_counts().head(25)

Location Description
STREET                            13577
RESIDENCE                          9696
APARTMENT                          5027
SIDEWALK                           4362
OTHER                              2071
PARKING LOT/GARAGE(NON.RESID.)     1614
RESIDENCE-GARAGE                    955
ALLEY                               938
SMALL RETAIL STORE                  929
RESIDENCE PORCH/HALLWAY             914
RESTAURANT                          904
DEPARTMENT STORE                    813
SCHOOL, PUBLIC, BUILDING            783
GROCERY FOOD STORE                  748
RESIDENTIAL YARD (FRONT/BACK)       692
CHA PARKING LOT/GROUNDS             645
VEHICLE NON-COMMERCIAL              618
GAS STATION                         526
COMMERCIAL / BUSINESS OFFICE        460
CHA APARTMENT                       458
PARK PROPERTY                       395
CTA PLATFORM                        295
BAR OR TAVERN                       265
HOTEL/MOTEL                         259
CHA HALLWAY/STAIRWELL/ELEVATOR      247
Name: count, dtype: int64

In [88]:
def group_location_final(loc):
    if pd.isnull(loc):
        return 'Other'

    loc = loc.upper()

    # 🏠 Residential
    if any(word in loc for word in [
        'RESIDENCE', 'APARTMENT', 'HOUSE', 'HOME', 'PORCH',
        'YARD', 'GARAGE', 'BASEMENT', 'ROOMING', 'CHA APARTMENT',
        'RESIDENTIAL'
    ]):
        return 'Residential'

    # 🏬 Commercial
    elif any(word in loc for word in [
        'STORE', 'SHOP', 'RETAIL', 'RESTAURANT', 'BAR', 'TAVERN',
        'BANK', 'OFFICE', 'BUSINESS', 'HOTEL', 'MOTEL',
        'GAS STATION', 'DRUG STORE', 'CURRENCY EXCHANGE',
        'DEALERSHIP', 'LAUNDROMAT', 'CLEANERS', 'PAWN'
    ]):
        return 'Commercial'

    # 🚗 Transportation
    elif any(word in loc for word in [
        'CTA', 'TRAIN', 'BUS', 'PLATFORM', 'TAXI',
        'VEHICLE', 'AIRPORT', 'AIRCRAFT', 'BOAT',
        'TRUCK', 'HIGHWAY', 'EXPRESSWAY', 'RAILROAD',
        'SUBWAY'
    ]):
        return 'Transportation'

    # 🏫 Institution
    elif any(word in loc for word in [
        'SCHOOL', 'COLLEGE', 'UNIVERSITY',
        'HOSPITAL', 'MEDICAL', 'POLICE',
        'JAIL', 'GOVERNMENT', 'CHURCH',
        'FACILITY', 'LIBRARY', 'FIRE STATION',
        'DAY CARE'
    ]):
        return 'Institution'

    # 🌳 Public / Outdoor
    elif any(word in loc for word in [
        'STREET', 'SIDEWALK', 'ALLEY',
        'PARK', 'LOT', 'FOREST', 'LAKE',
        'RIVER', 'FIELD', 'PRAIRIE',
        'BRIDGE', 'DUMPSTER', 'GANGWAY'
    ]):
        return 'Public'

    # ❓ Everything else
    else:
        return 'Other'

In [89]:
df['Location_Group'] = df['Location Description'].apply(group_location_final)

In [90]:
df['Location_Group'].value_counts()

Location_Group
Public            20086
Residential       19738
Commercial         5942
Other              2781
Transportation     1776
Institution        1702
Name: count, dtype: int64

In [91]:
df = pd.get_dummies(
    df,
    columns=['Location_Group', 'Primary Type'],
    prefix=['Loc', 'Crime']
)

In [93]:
df

,Block,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,Year,...,Crime_OTHER NARCOTIC VIOLATION,Crime_OTHER OFFENSE,Crime_PROSTITUTION,Crime_PUBLIC PEACE VIOLATION,Crime_RITUALISM,Crime_ROBBERY,Crime_SEX OFFENSE,Crime_STALKING,Crime_THEFT,Crime_WEAPONS VIOLATION
0,059XX S INDIANA AV,POSS: CANNABIS MORE THAN 30GMS,STREET,1.0,0.0,233.0,2.0,42.0,25.0,2001.0,...,False,False,False,False,False,False,False,False,False,False
1,027XX N LAWNDALE AV,SIMPLE,RESIDENCE,0.0,0.0,2524.0,25.0,42.0,25.0,2001.0,...,False,False,False,False,False,False,False,False,False,False
2,048XX W FULLERTON AV,HARASSMENT BY TELEPHONE,DRUG STORE,0.0,0.0,2521.0,25.0,42.0,25.0,2001.0,...,False,True,False,False,False,False,False,False,False,False
3,052XX W DIVISION ST,HARASSMENT BY TELEPHONE,STREET,0.0,0.0,2532.0,25.0,42.0,25.0,2001.0,...,False,True,False,False,False,False,False,False,False,False
4,022XX S KEDVALE AV,HARASSMENT BY TELEPHONE,RESIDENCE,0.0,1.0,1013.0,10.0,42.0,25.0,2001.0,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52078,003XX W 103RD ST,SIMPLE,DEPARTMENT STORE,0.0,0.0,511.0,5.0,9.0,49.0,2015.0,...,False,False,False,False,False,False,False,False,False,False
52079,010XX N LATROBE AVE,DOMESTIC BATTERY SIMPLE,SIDEWALK,0.0,1.0,1524.0,15.0,37.0,25.0,2015.0,...,False,False,False,False,False,False,False,False,False,False
52080,031XX S PULASKI RD,SIMPLE,PARKING LOT/GARAGE(NON.RESID.),1.0,0.0,1031.0,10.0,22.0,30.0,2015.0,...,False,False,False,False,False,False,False,False,False,False
52081,066XX N ASHLAND AVE,TO PROPERTY,RESIDENCE,1.0,0.0,2432.0,24.0,40.0,1.0,2015.0,...,False,False,False,False,False,False,False,False,False,False
52082,015XX,SIMPLE,STREET,0.0,0.0,1834.0,8.0,42.0,25.0,2015.0,...,False,False,False,False,False,False,False,False,True,False

In [94]:
df.to_csv("data_preprocessed.csv", index=False)